language: python
sudo: false
matrix:
  include:
  - python: 2.7
  - python: 3.2
  - python: 3.3
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: nightly
  - python: pypy3
  allow_failures:
  - python: 3.2
  - python: 3.3
  - python: nightly
install:
- pip install -e .
script:
- python setup.py test
deploy:
  provider: pypi
  user: dtkav
  password:
    secure: phtFKO18YZlBDyXgKYvjVdpkCuCW+GB/5T8IXfD0PJrfiCbuQ0qvvLWNXNMAYlX11F7yJh2qsREQPL8WTsG+CdFikAs//Km5n10wbeWDZ4kHmUXBz3IRLgLymPh4aw3KJaMbNsXDDu+cVolYeaa8+BI3wfBX8+hvbK3/ogIKEf8Y4qCKH3fXxwUweGpK+IYYhPlUE4JBHZFicmn9TFp2Mb3p/HVwXGcPUWHAeoSLTv4LCfynrxX4A6rvMNYL3D2AghgbZJMMjI5xAue+P3GFMjZUo5nJXNPGtGc6prJ9+835TJ2eNcUSQ3u1sXd5gRSPQ8Xcn48d0G/4YLvSUwowB/GP/fP4afE4NXyqe/W7//4VFL+cTh97Qcb8A+KZVt2OQ5E7RdsQE3P/nNtya+Bxa6TsKtmNQSSmJAWB5vY1B2ijomAGgM8rTCkzLAkUEUBgFUiFBzDDLgISddmvKp8q3Jvtm+xl1bT3Sx8X4ds0SwMlaZSIIscYlX+4pSu9yajDKtxKxiTKippzekxjANbtADhaoUdvSLF6JCIjIOw7snlTwYJn9FoylCmr9OHX2apwII5Bg/xyHQf1chBV15pbqdUcmMw8Wyohjf3qArWGdX1ZCQZ7JdkLeeZbodNJm4TVtlDuDf//u1iBJY1YwaneNKtdqGG8wmeNAYcyR9udCG4=
  distributions: sdist bdist_wheel
  on: 
tags: true
