language: python
sudo: false
matrix:
  include:
  - python: 2.7
  - python: 3.2
  - python: 3.3
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: nightly
  - python: pypy3
  allow_failures:
  - python: 3.2
  - python: 3.3
  - python: nightly
install:
- pip install -e .
script:
- python setup.py test
deploy:
  provider: pypi
  user: dtkav
  password:
    secure: AHlBQhK/3X5bInLe++7MsEVm+6/L4kMsLBTRRD3udZGRBNKA1WvzX5/zM8+WmSpjbvs133eYfa/B7DA39oV4cin/4gG5Mqx6aB+jKAseNdmnOOkGYCLaYwdIUIkAyV7eMdh2mCIzIwR8FVtzS4gLVz8szwO48ETo/8rCAXACUS3hiTrojB1ffUYTAQ+RuE5wzRSVsub14aW9/gaz3ExBgEsD5xgY92mG9sJbosOv+uRZ6FAHXnCizRL+McvDkVdWcsdAW+vFE4cKkO2zciE76cXy59IUbEnd3DmOiCA9vAzlQ95PBQVJbUaF7pyASP5m1/KcrXTnBVj1BDcMDrwzTIXoaRd/eMzs0P/jUveigwK86E9dTZZGl1ezyoTIBhxgcgAbUJEp7hHR7mVxN9Sl6tePiOnBiCDOFTelhz4hnEQoFZ2CfO9KrfNWc2Us8kD3W5vesN4DierTjM+YyLc9t3eb7zv8mtpXQrrEB5lAtttZ/P+0ZOG+aJRLvb6OYSxVlapw2R4z1m2K1vTe23wm2ryfh7GM7Su/t1c8CLOWYbgMleqiOiWMhOguz5tSIMsunSpDERouR5Y32uGDfPA65uVabpRuI4R0nBnCqYJiHmOWE/XO+zM+YgN0aHOKzBusHpA7RkFZv2xZ3MupmWuKVd+VFAMhHTpZT3Ob4wQz5z8=
  distributions: sdist bdist_wheel
  on: 
    tags: true
