language: python
sudo: false
matrix:
  include:
  - python: 2.7
  - python: 3.2
  - python: 3.3
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: nightly
  - python: pypy3
  allow_failures:
  - python: 3.2
  - python: 3.3
  - python: nightly
install:
- pip install -e .
script:
- python setup.py test
deploy:
  provider: pypi
  user: dtkav
  password:
    secure: G4cFt0h7l/Bk8hu6Idwu/7hAUrI7tymI8Qab2M/g0Mqs53+crCyGIsU06KG2FMcyQ9tQKqf9uGISPD3YkyP4nCOtHUwB2XMsMvEdJLWCvzYCPOb7HsTZdkRs8VSucEAIaJOUAiKxEGldv637ADoVunxM5RNWc2woIEq0hXAey89gNUNEE9B0SI6WC8/gC3r0kJ04cHs6wiS44afeeB/b7vbw5hDdueDHXJF4gjAVSfqEOPBAjUsN5PbX+OALTC2xg9f9rFcUR/VypJNmuEJL1kF1tpooJ7oXeri/pFnJ09UGm335kj/8ngrN2wbGIcJNpDGekMVQREMbKTVIuE0pxSiCNLmZuiYpwPBWD3FBScQYy/ed/goVbJ+7D0ZySLMuFDL913Wgi/tYdfBnZDt2EB9EC5Shp4PX5sBRIswh2SgJ67cEJOrDFhexWUN7iy6Id7D+Bwz9u+lzIIb149nAeI600Y7k57s7Om13twqkiHYhH/PFm8780q9icGEQ/TMgYWRS0RAOAU4wWyHtshJ+0Q1W0XeO7lFcSQ7xaewkiRFeuPyJ3wuIXxK5UssQAJgLH5qYgiDuMXJe6rz2yvT8KB4nQvv1Z4VyQlb3ihMq2mdXNMkr1w9R8oJ3Hs5LWNcob8Ptpzd29qYrWwkDhYX7yQX9lW2flBB21ZOi8ZEeeWE=
  distributions: sdist bdist_wheel
  on: 
tags: true
